### PR TITLE
Implement Vector class

### PR DESCRIPTION
**Pull request by MrGallo**
Create `vector.py` Vector class.
Modify `sprite.py`. Create `VectorSprite` class which uses `Vector` for position and velocity
Implement tests for `Vector` class.

Decided to have `VectorSprite` extend `Sprite` because there is a minor trade-off in performance if we implement `Vector`s with the original `Sprite` class.

### CODE REVIEW

**Comment by MrGallo** [comment]
Performs quite poorly on `arcade\examples\perf_test\stress_test_draw_moving_arcade.py`. Almost doubles the processing time. :(

**Comment by SirGnip** [comment]
Would there be any performance benefit to have your Vector class not derive from `list`, but use `__slots__` instead?  I created a simple Vector class (`_Vec2`) in https://github.com/SirGnip/arcade/blob/master/arcade/utils.py for use by the Particle system and used slots (see https://github.com/SirGnip/arcade/blob/master/arcade/utils.py#L71).  I didn't try using my `_Vec2` class in `sprite.py`, so I have no idea how it performs (though using `__slots__` was much faster than not using `__slots__`)

**Comment by MrGallo** [comment]
I edited my comment above concerning `__slots__`. I never tested that version against the `arcade\examples\perf_test\stress_test_draw_moving_arcade.py` test.

**Comment by SirGnip** [comment]
Ah!  Too bad.  A vector class is extremely convenient.

Is it maybe worth having a Vector class in arcade, but not use it for sprite.py (kind of what I did for the particle systems)?  This allows us to have a nice Vector class when needed, but the core of arcade isn't paying the performance tax of it...  Just brainstorming...

**Comment by MrGallo** [comment]
Maybe I should work on a `VectorSprite(arcade.Sprite)` subclass that will make use of an `arcade.Vector` for `position` and `velocity`, should one desire to use it. Thoughts?

**Comment by pvcraven** [comment]
I'm trying to see about implementing SpriteList/Sprite with a C-language base. I want to be faster than PyGame at everything, and I can't right now because these operations are just so much faster in C.

**Comment by MrGallo** [comment]
In the meantime I would like to add the `Vector` class to arcade and extend `Sprite` with a `VectorSprite` class. I'll be modifying the pull request code soon.

**Comment by sbischoff-ai** [comment]
For fast C-based linear algebra in Python the obvious choice would be to just use numpy.
I'd recommend implementing a wrapper around numpy arrays with a more pythonic API for 2D Vectors, Matrices and utils for common geometric transformations.

I could start working on that and on refactoring existing 2D math calculations accordingly.

**Comment by pvcraven** [comment]
You would think numpy would be faster, but it isn't. The VBOs for OpenGL use Numpy and that's the main performance bottleneck the code has.

Numpy is fast when the numbers are in numpy. But going from Python storate to Numpy storage and back is slow. Pyglet and PyGame use native C types are are faster.

My long-term plan (starting around December) is to dive in and make the base class compile in C. This is hard because OpenGL drawing requires all data in a sprite list to be in a continuous block on memory. So sprites have to know where in the block they are. If indeed, they are in a block yet.

**Comment by astronouth7303** [comment]
Hey, Astra from the PursuedPyBear project. We implemented [ppb-vector](https://github.com/ppb/ppb-vector/) already, and I thought I'd weigh in with our experience.

First of all, the golden rule of trying to optimize: Always have benchmarks, always follow the data. Examples:

* `__slots__` is faster than `__dict__`, even with some of the extra calls involved in their implementation. (At the time, I thought it was primarily a memory optimization.)
* Caching is often slower than just recomputing. We originally memoized the vector length, but we found that the memoization code was slower than the floating point operation.

As for C/Python, while yes C versions would be faster, for us we found that PyGame (and SDL1)'s render model was our biggest bottleneck, not our pure-python mechanics. We consider our current pure-python implementation Good Enough for now. Your milage may vary and always approach performance problems with data in-hand. (That said, we did experiment with pyglet and pygame and found even an initial implementation of pyglet-based rendering to be a dramatic improvement. The effort was abandoned because at the time pyglet had crashing bugs on mac, and that was unacceptable for us.)

I had mentally noodled with the idea of a next-gen version of ppb-vector that included bulk transformation features and could juggle vector buffers, but we have not needed it so far.

Even on my pretty-old T420, our performance bottlenecks are rooted in pygame/sdl1, not our code. That said, our goals are explicitly education-focused, which means that we want to focus on ease of use and readability over maximum performance or scale.

(I will also shamelessly plug and say that ppb-vector was spun out into its own project partly in hopes that other people will use it, and you are more than welcome to either vendor it or just use the package. We consider it stable with a pretty decent test suite.)

**Comment by pvcraven** [comment]
Hey, thanks for the reference!

There are a lot of attempts at structure that I've found slower, and I agree that 'follow the data' is the way to go.

PyGame's drawing is super-slow. But its collision detection, in pure C, is really fast. We do spatial hashing in pure python and PyGame's C code with a straight n^2 order still performs just as well.

The time it takes to move between local storage and a block of memory set up for OpenGL rendering is a bottleneck for me. I haven't had time to try __slots__, but it is on my radar.

This is an area of the code I don't want to do changes in until it is both faster, and programmatically better.

**Comment by astronouth7303** [comment]
I would not _expect_ moving to `__slots__` to make the copy to an OpenGL buffer somewhat faster, because it improves access times.

That said, I would _expect_ real improvements to come from more aggressive and systemic management of vector buffers. (eg, user-visible vector objects are allocated out of pre-sized vector buffers, and you write code to manage the alloc/dealloc lifecycle of those buffers and their contents.) Unfortunately, I'm only vaguely familiar with OpenGL mechanics and don't really know the specifics of operation performance.

**Comment by pvcraven** [comment]
At this point, I've done the optimization pass that I wanted to. This was the reason for delaying this PR. Not sure if we'd be better off with our own vector, use something like ppb-vector? Not do anything? I'd like  to move away from numpy as a dependency, so I'd prefer not to use  that.

Performance has to be in-line.

**Comment by MrGallo** [comment]
I don't mind if this gets dropped as long as there is the option to refer to position and speed as vectors and use vector methods on them.

**Comment by pvcraven** [comment]
Closing this. We need a new PR that builds without conflict and runs as fast as current implementation.

**Pull request closed without merging**
