### PR TITLE
Tiny modification when returning

### PR DESCRIPTION
**Pull request by Aareon**
Simply remove another variable when completing the task, then returning the value necessary.

Seems a better alternative to creating a variable with a default value, performing a check, modifying said variable if necessary, and returning.

### CODE REVIEW

**Comment by Aareon** [comment]
Travis is *screaming* with errors mostly pertaining the values being undefined. Not sure if that’s due to the nature of the environment, but I’m not entirely sure if the build failure is necessarily my fault.

**Comment by pvcraven** [comment]
Merged, thanks.

**Comment by Aareon** [comment]
@pvcraven No problem! If you’d prefer, I can also PR [#169](https://github.com/pvcraven/arcade/issues/169)

**Comment by pvcraven** [comment]
If it is an improvement, I'll happily take it!

**Pull request merged**
