### PR TITLE
resizing

### PR DESCRIPTION
**Pull request by pauleveritt**

### CODE REVIEW

**Comment by pvcraven** [comment]
Hm, any idea why TravisCI is upset with arcade.application.Window.set_maximum_size?

**Comment by pauleveritt** [comment]
It seems to be a doctest issue. Everything runs fine locally in OS X. I started installing various Parallels VMs yesterday to try and run arcade in Windows and Linux before pushing but ran out of time.

I’m running Python 3.6b3 locally. I wonder if that’s the issue.

I’ll get this fixed soon.

—Paul

**Comment by pauleveritt** [comment]
I was able to recreate the Travis test failures on Linux and Python 3.5.

**Comment by pauleveritt** [comment]
@pvcraven Hmm, it seems that running on Linux doesn't like creating two windows in one test:

```python
        >>> import arcade
        >>> window1 = arcade.Window(200, 100, resizable=True)
        >>> window1.set_maximum_size(200, 200)
        >>> window1.close()
        >>> del window1
        >>> window2 = arcade.Window(200, 100, resizable=False)
        >>> window2.set_maximum_size(200, 200)
        Traceback (most recent call last):
        ...
        ValueError: Cannot set max size on non-resizable window
        >>> window2.close()```

Here's the error, on Linux:

```python
Error
**********************************************************************
File "/home/pauleveritt/projects/arcade/arcade/application.py", line 129, in Window.set_maximum_size
Failed example:
    window2 = arcade.Window(200, 100, resizable=False)
Exception raised:
    Traceback (most recent call last):
      File "/home/pauleveritt/projects/pycharm-community-2016.2.3/helpers/pycharm/docrunner.py", line 140, in __run
        compileflags, 1), test.globs)
      File "<doctest Window.set_maximum_size[5]>", line 1, in <module>
        window2 = arcade.Window(200, 100, resizable=False)
      File "/home/pauleveritt/projects/arcade/arcade/application.py", line 30, in __init__
        resizable=resizable)
      File "/home/pauleveritt/projects/arcade/env35/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
        super(XlibWindow, self).__init__(*args, **kwargs)
      File "/home/pauleveritt/projects/arcade/env35/lib/python3.5/site-packages/pyglet/window/__init__.py", line 558, in __init__
        self._create()
      File "/home/pauleveritt/projects/arcade/env35/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 349, in _create
        self.set_minimum_size(self._width, self._height)
      File "/home/pauleveritt/projects/arcade/arcade/application.py", line 109, in set_minimum_size
        raise ValueError('Cannot set min size on non-resizable window')
    ValueError: Cannot set min size on non-resizable window


Failure
**********************************************************************
File "/home/pauleveritt/projects/arcade/arcade/application.py", line 130, in Window.set_maximum_size
Failed example:
    window2.set_maximum_size(200, 200)
Expected:
    Traceback (most recent call last):
    ...
    ValueError: Cannot set max size on non-resizable window
Got:
    Traceback (most recent call last):
      File "/home/pauleveritt/projects/pycharm-community-2016.2.3/helpers/pycharm/docrunner.py", line 140, in __run
        compileflags, 1), test.globs)
      File "<doctest Window.set_maximum_size[6]>", line 1, in <module>
        window2.set_maximum_size(200, 200)
    NameError: name 'window2' is not defined


Error
**********************************************************************
File "/home/pauleveritt/projects/arcade/arcade/application.py", line 134, in Window.set_maximum_size
Failed example:
    window2.close()
Exception raised:
    Traceback (most recent call last):
      File "/home/pauleveritt/projects/pycharm-community-2016.2.3/helpers/pycharm/docrunner.py", line 140, in __run
        compileflags, 1), test.globs)
      File "<doctest Window.set_maximum_size[7]>", line 1, in <module>
        window2.close()
    NameError: name 'window2' is not defined
```

Works fine on macOS. Obviously I can limit one doctest to one window to shut this up, but that's not a good solution. I tried arcade.close_window() but no luck. Any thoughts?

**Comment by pvcraven** [comment]
I once experienced a similar error. I had to manually run garbage collection to finish cleaning up the first window before the second could be built. Don't know if this might be the same cause or not.

**Comment by pauleveritt** [comment]
@pvcraven My various attempts at deleting the reference then calling arcade.close_window() or even gc.collect() manually, didn't work. Two choices I can think of:

- I slim down the unit tests and only test one possibility (decreasing the coverage)
- I move some of the testing out of doctests

Preference, or any other ideas?

**Comment by pauleveritt** [comment]
I wound up moving some of the testing out of doctest (though I haven't wired it back in.) I then ran into an issue on Linux, the xlib implementation calls set_minimum_size even when resizable is false. I renamed my arcade wrappers to set_min_size and set_max size.

**Pull request merged**
