### PR TITLE
Fix naming of x and y coordinates in *_xywh_* functions

### PR DESCRIPTION
**Pull request by eruvanos**
Fixing issue #225

### CODE REVIEW

**Comment by LexVerheesen** [comment]
Thank you for your pull request.
Would be great if we also changed the description a bit.

How about:
> Draw a rectangle by specifying left, right, top, and bottom edges.
Draw a rectangle extending from bottom left to top right

> :bottom_left_y: The y coordinate of the top of the rectangle.
:bottom_left_y: The y coordinate of the bottom of the rectangle.

**Comment by eruvanos** [comment]
I changed the docs and in addition added some more docs for draw_xywh_rectangle_textured.
Furthermore added some parameters, that are also available in draw_texture_rectangle.

**Comment by pvcraven** [comment]
Thanks! Happy to merge this in, if you could address the PEP thing with spaces in parameters:
https://www.python.org/dev/peps/pep-0008/#other-recommendations

**Comment by eruvanos** [comment]
I changed it, just checked with pep8: 
> When combining an argument annotation with a default value, use spaces around the = sign (but only for those arguments that have both an annotation and a default).
>Yes:
>
>def munge(sep: AnyStr = None): ...
>def munge(input: AnyStr, sep: AnyStr = None, limit=1000): ...
>No:
>
>def munge(input: AnyStr=None): ...
>def munge(input: AnyStr, limit = 1000): ...

Give me a hint weather I should change it back :)

**Comment by eruvanos** [comment]
Any requirements left?
Greetings

**Comment by pvcraven** [comment]
Thanks!

**Pull request merged**
