### PR TITLE
Update sound.py

### PR DESCRIPTION
**Pull request by zeziba**
Issue: #229

Add a Player class to make management of background music easier.

### CODE REVIEW

**Comment by pvcraven** [comment]
Thanks! I'm away from a computer this week. I'll look at your PR in detail next week.

**Comment by pauleveritt** [comment]
The doctest at:

```
229         >>> player.load_dir("arcade/examples/sounds/")
```

...fails on macOS with:

```
Expected nothing
Got:
    Warning: .ogg (Ogg Vorbis) files are not compatible with the Mac on the Arcade library.
    Warning: .ogg (Ogg Vorbis) files are not compatible with the Mac on the Arcade library.
    Warning: .ogg (Ogg Vorbis) files are not compatible with the Mac on the Arcade library.
```

I can make a new ticket for this if you'd like.

**Comment by zeziba** [comment]
If you know how to get the doctest to check for a specific version and change its behavior based on that I will add it to the doc string but I removed it and put the general use case that I was going for.

**Comment by pauleveritt** [comment]
When you say “specific version”, can you explain what you mean?

But yes, in general the doctests are not as featured as regular pytest tests. For example, .travis.yml shows the use of markers to restrict what tests won’t work right on Travis.

—Paul

**Comment by zeziba** [comment]
If it is mac os it will output the x3 warnings as of right now because there are that many .ogg files in that specific directory. The player is not designed to handle the implementation errors from the file loader as it relies on the arcade implementation to always have play_sound as it backbone so if it changes the player changes as well.

Adding os specific markers would allow for the doctests though I have little knowledge of travis.

**Comment by pauleveritt** [comment]
As a suggestion, have the docstring point at a directory which only contains .wav sounds, meaning, sounds which can play on all platforms. The docstring's purpose is to show loading all files in a directory, not loading different kinds of sounds.

**Comment by zeziba** [comment]
Well, from a testing standpoint I would like it to fail when the file type is unsupported. This will ensure compliance with how the function is supposed to work in the future. In that vein is there a way to run multiple doctests on the same file? This would allow for it to run the test for all three systems by changing the flags pertaining to the system.

**Comment by pauleveritt** [comment]
As you noted, the handling of file types per platform is further downstream than your code. Your code should just presume it works, at least from a unit test perspective. We can write some non-doctests for the sound.py in Arcade if we want per-platform exceptions, IMO. Just my two cents.

I don't know of the right way to parameterize doctests. (I'd argue that it's abusing the purpose of doctests.)

**Pull request merged**
