### PR TITLE
Add SoLoud support for Linux

### PR DESCRIPTION
**Pull request by chpurdy**
Partial fix for issue #372 

I was able to get the SoLoud library to build and added the dynamic library.  I built it using the compile flag -lasound to get rid of the linking errors (I saw your previous problems).

### CODE REVIEW

**Comment by chpurdy** [comment]
I don't understand why the package builds are failing.  It says it cannot find soloud module, but I've done everything I can come up with to get it working.

**Comment by chpurdy** [comment]
Resolves issue #519

**Comment by pvcraven** [comment]
Getting ``/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found`` which I think means your distro is more recent than mine. Researching...

**Comment by chpurdy** [comment]
> Getting `` /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found `` which I think means your distro is more recent than mine. Researching...\
> 
> Update, I seem to be running 2.27-3 on my Ubuntu. I wonder if there's a way to compile this thing to make it more platform-independent.

If you build soloud using the -lasound flag, does it run?  I wonder if it's backward compatible somehow...ie. use an older version of glibc to maximize systems that can use it?

**Comment by pvcraven** [comment]
I upgraded to Ubuntu 19 from Ubuntu 18 LTS. Now I get:

 ``ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave``

**Comment by pvcraven** [comment]
Ok, fixed that error by creating a ``~/.acoundrc`` file with:

```
pcm.!default {
	type hw
	card 1
}
```

**Comment by akapkotel** [comment]
As for now (tested on Linux Mint 19.3 Tricia), SoLoud does not work - "unable to load soloud_dll".

**Comment by pvcraven** [comment]
> As for now (tested on Linux Mint 19.3 Tricia), SoLoud does not work - "unable to load soloud_dll".

Any way you can paste the complete error?

**Comment by akapkotel** [comment]
> > As for now (tested on Linux Mint 19.3 Tricia), SoLoud does not work - "unable to load soloud_dll".
> 
> Any way you can paste the complete error?

When starting arcade-window:

SoLoud dynamic link library /home/akapkotel/Programowanie/Python/PyCharm projects/pytanks/venv/lib/python3.6/site-packages/arcade/soloud/libsoloud.so not found.
Warning, can't initialize soloud name 'soloud_dll' is not defined. Sound support will be limited.

**Comment by chpurdy** [comment]
Linux Mint is based on Ubuntu 18.04.  I have not been able to get Soloud working in 18.04.  For some reason the ALSA library won't link correctly.

**Comment by pvcraven** [comment]
What happens when you link it? Maybe that's why I had so many problems trying to compile it myself because I was originally on 18.04.

**Comment by chpurdy** [comment]
> What happens when you link it? Maybe that's why I had so many problems trying to compile it myself because I was originally on 18.04.

When I try to run it, I get the error: `undefined symbol: snd_pcm_close`

This seems to be caused by it not correctly getting the ALSA library, `/usr/lib/libasound.so`.  I'm using the `-lasound` compile flag when building Soloud (which fixed it on my Arch system) but that doesn't help.

If I add `shared_library = ctypes.CDLL("libasound.so",mode=ctypes.RTDL_GLOBAL)` before loading the Soloud library (in `soloud.py`) the program will run, then I get the error 
```
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
```
Creating the .asoundrc as described above gets rid of the error, but still no sound.

**Pull request merged**
