### PR TITLE
Fix typo & add rounding to points of sprite

### LINKED ISSUE #128: PhysicsEnginePlatformer infinity loop
```
                    while check_for_collision(self.player_sprite, item):
                        self.player_sprite.bottom = item.top
```
at line 133 in `arcade/physics_engines.py` infinity loops when my `AnimatedWalkingSprite` falls on a platform. The problem is that `item.top` is 32 and `self.player_sprite.bottom` is 31.99999999996 :)

Took ~8 hours to find that...

Thing is, I can't quite follow the math behind the engine. Can someone help me solve it?

### PR DESCRIPTION
**Pull request by dzervas**
Fixes #128

### CODE REVIEW

**Comment by dzervas** [comment]
Why look at that! I managed to break half the tests with 2 lines of code that actually fix my problem!
That's what I call 😎 *NINJA SKILLS*

**Comment by dzervas** [comment]
Yey! Fixed it. Sorry for the mess, just forgot to run the tests locally

**Comment by pauleveritt** [comment]
@pvcraven These commits look good to me. If it's ok with you, I'll merge them and make sure the tests run ok.

**Comment by pvcraven** [comment]
Sounds great, thanks!

**Comment by pvcraven** [comment]
Ok, the code changed too much since this pull request. I manually merged in the rounding, and I'll close this pull request. Hopefully this will fix it.

**Pull request closed without merging**
