### PR TITLE
Added Travis CI badge

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by pvcraven** [comment]
Thanks. Figuring out badges is on my 'list-of-things-to-do.'

**Comment by mikemhenry** [comment]
No problem! It should be on the bottom of your 'list of things to do'. I'm
interested in seeing where this goes!

**Comment by pvcraven** [comment]
Hm, doesn't work well here:

https://pypi.python.org/pypi/arcade/0.0.3a12

Know any magic to keep it from showing up in that context?

Paul Vincent Craven

**Comment by mikemhenry** [comment]
Looks like pypi rolled back markdown support and uses restructured text.
I'll see if there is an easy fix, poking around other projects look like
some are just letting it look that way.

**Comment by pvcraven** [comment]
Just got more of them to work:

http://arcade.readthedocs.org/en/latest/


Paul Vincent Craven

**Comment by mikemhenry** [comment]
Sweet! Have you looked into integrating something like coveralls? It will
measure how much tests cover the code base.

**Comment by pvcraven** [comment]
Yes, I really want to do that. 

I'm using doc strings to test rather than separate unit tests. So far I kind of like it. 

Paul Vincent Craven

**Comment by pvcraven** [comment]
Ha! Got coveralls working:

http://arcade.readthedocs.org/en/latest/


Paul Vincent Craven

**Comment by mikemhenry** [comment]
Awesome!

**Pull request merged**
