### PR TITLE
Added gui.py and gui_test.py for GUI BUTTONS

### PR DESCRIPTION
**Pull request by wamiqurrehman093**
GUI ELEMENTS #475

I have made GUI Button Classes and added their tests too everything works fine.

### CODE REVIEW

**Comment by wamiqurrehman093** [comment]
After running make testcov it says: 46 passed and 20 warnings in 16.45s.

**Comment by pvcraven** [comment]
This is a good start. I'd like to see a bit more flexibility for a button we actually merge in.

* on_press / on_release should probably be abstract and easy to override without worrying about disabling functionality
* Need to hook into main program loop, so if we create the button, we can 'add' it to the window and have it get auto-called.

**Comment by wamiqurrehman093** [comment]
Okay sir Thank you I will update it soon

**Comment by wamiqurrehman093** [comment]
Sir i have made the methods abstract but I am kind of confused on how to add it to the main program loop... this is my first pull request so can you help please

**Comment by wamiqurrehman093** [comment]
Sir I have added it to the window and view class mouse press/release buttons as an exception with to update it automatically

**Comment by pvcraven** [comment]
Awesome! I'll check this out as soon as I get a chance. We need button functionality.

**Comment by wamiqurrehman093** [comment]
Yes sir! it is related to tile map issues not the GUI file and right now I am coding a text box I hope I finish it soon.

**Comment by wamiqurrehman093** [comment]
Sir I have added the basic functionalities of GUI like _Texts_, _Text_ _Boxes_, _Dialogue_ _Boxes_ and _Buttons_ and I have added them all to the main program loop. we have to call "**super().on_draw()**" inside the **on_draw** method after "**arcade.start_render()**" and add _buttons_, _textboxes_, _dialogueboxes_ and _texts_ in **window's** (or **view's**) object's lists:

- self.button_list
- self.dialogue_box_list
- self.text_list
- self.textbox_list

**Pull request merged**
