### PR TITLE
Remove OpenGL dependency from test_view.py so it can run via Travis CI #461

### PR DESCRIPTION
**Pull request by SirGnip**

### CODE REVIEW

**Comment by SirGnip** [comment]
CI is failing.  Should be able to fix this.

**Comment by SirGnip** [comment]
A couple attempts to mock out Window and move it to unit/ and no success...  Unless someone feels strongly, I'm going to abandon this.

**Comment by pvcraven** [comment]
The CI is nice, but because of things like this I've just concentrated on running things local.

**Comment by SirGnip** [comment]
Not worth the effort.  Leaving `test_view.py` in `unit2/`

**Pull request closed without merging**
